version: '3.8'
services:
  nginx:
    build: .
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - one-api
    networks:
      - app-network

  one-api:
    image: justsong/one-api-en
    container_name: one-api
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /home/ubuntu/data/one-api:/data
    expose:
      - "3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
