version: '3'
services:
  one-api:
    image: justsong/one-api-en
    container_name: one-api
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /home/ubuntu/data/one-api:/data
    expose:
      - "3000"

  nginx:
    build: .
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - one-api
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
